config:
  line-length: false
  no-bare-urls: false
  blanks-around-headings: false
  blanks-around-lists: false
  blanks-around-fences: false
  blanks-around-tables: false
  no-duplicate-heading: false
  no-trailing-punctuation: false
  no-emphasis-as-heading: false
  fenced-code-language: false
  first-line-heading: false
  table-column-style: false
  no-blanks-blockquote: false
  no-multiple-blanks: false
  no-missing-space-atx: false
  single-title: false
  heading-increment: false
  no-inline-html: false
  ul-indent: false
  ol-prefix: false
ignores:
  - "blog/**"
  - "research/**"
  - "target/**"
