identity:
  name: "daneel"
  type: rust
  version: "0.9.1"

description: >
  Live technical fiction exploring architecture-based AI alignment.
  Implements a cognitive architecture (TMI) in Rust with actor-based
  concurrency, Redis Streams for thought competition, and Qdrant for
  semantic memory. The thesis: architecture produces psychology.

stack:
  - Rust (tokio, ractor actors, axum)
  - Redis Stack (streams, JSON)
  - Qdrant (vector memory)
  - Docker Swarm
  - Hugo (blog)

conventions:
  - "Result<T, E> for errors, no panics or unwrap() in library code"
  - "clippy pedantic + nursery, zero warnings"
  - "100% test coverage on testable code (#[coverage(off)] for I/O)"
  - "Colocated tests (#[cfg(test)] mod tests)"
  - "ADR format in docs/adr/ for architectural decisions"
  - "One sentence per line in docs (for git diffs)"
